
const PILLARS=[
  {id:"cmi",num:"01",icon:"\uD83C\uDFE5",name:"Clinical Medicine Institute",tagline:"Disease. Diagnosis. Treatment. Mastery.",color:"#8B1A4A",type:"education",
   desc:"Comprehensive multidisciplinary disease-based courses covering pathophysiology, diagnostics, laboratory science, pharmacotherapy and non-pharmacological management.",
   categories:[
    {name:"Obstetrics & Maternal Health",icon:"\uD83E\uDD30",courses:[
      {id:"pe",title:"Preeclampsia & Eclampsia",sub:"Storm in the Womb",status:"live",icon:"\uD83E\uDDEC",dur:"19h+",modules:7},
      {id:"oh",title:"Obstetric Haemorrhage",sub:"When Blood Won't Stop",status:"live",icon:"\uD83E\uDE78",dur:"12h",modules:5},
      {id:"ms",title:"Maternal Sepsis",sub:"The Silent Invasion",status:"soon",icon:"\uD83E\uDDA0",dur:"10h",modules:4},
      {id:"gd",title:"Gestational Diabetes",sub:"Sweet But Dangerous",status:"soon",icon:"\uD83C\uDF6C",dur:"10h",modules:4},
      {id:"ptl",title:"Preterm Labour",sub:"Born Too Soon",status:"soon",icon:"\uD83D\uDC76",dur:"8h",modules:4},
      {id:"ep",title:"Ectopic Pregnancy",sub:"Out of Place",status:"soon",icon:"\u26A0\uFE0F",dur:"6h",modules:3},
      {id:"hg",title:"Hyperemesis Gravidarum",sub:"Beyond Morning Sickness",status:"soon",icon:"\uD83E\uDD22",dur:"5h",modules:3},
    ]},
    {name:"Neonatology & Paediatrics",icon:"\uD83D\uDC76",courses:[
      {id:"nr",title:"Neonatal Resuscitation",sub:"The First Breath",status:"soon",icon:"\uD83D\uDCA8",dur:"8h",modules:4},
      {id:"nj",title:"Neonatal Jaundice",sub:"Yellow Alert",status:"soon",icon:"\uD83D\uDFE1",dur:"6h",modules:3},
      {id:"cp",title:"Childhood Pneumonia",sub:"Breathing for Life",status:"soon",icon:"\uD83E\uDEB1",dur:"8h",modules:4},
      {id:"cm",title:"Childhood Malaria",sub:"The Child's Battle",status:"soon",icon:"\uD83E\uDD9F",dur:"8h",modules:4},
      {id:"pmal",title:"Paediatric Malnutrition",sub:"Feeding the Future",status:"soon",icon:"\uD83C\uDF7D\uFE0F",dur:"7h",modules:3},
    ]},
    {name:"Infectious Diseases",icon:"\uD83E\uDDA0",courses:[
      {id:"mal",title:"Malaria",sub:"Africa's Oldest Enemy",status:"soon",icon:"\uD83E\uDD9F",dur:"12h",modules:5},
      {id:"tb",title:"Tuberculosis",sub:"The White Plague Returns",status:"soon",icon:"\uD83E\uDEB1",dur:"12h",modules:5},
      {id:"hiv",title:"HIV & AIDS",sub:"Four Decades On",status:"soon",icon:"\uD83D\uDD34",dur:"14h",modules:6},
      {id:"typh",title:"Typhoid Fever",sub:"Waterborne Danger",status:"soon",icon:"\uD83D\uDCA7",dur:"8h",modules:4},
      {id:"men",title:"Meningitis",sub:"Attack on the Brain",status:"soon",icon:"\uD83E\uDDE0",dur:"10h",modules:4},
      {id:"chol",title:"Cholera",sub:"The Blue Death",status:"soon",icon:"\uD83D\uDCA7",dur:"6h",modules:3},
      {id:"den",title:"Dengue Fever",sub:"Break-Bone Fever",status:"soon",icon:"\uD83E\uDD9F",dur:"8h",modules:4},
      {id:"hepb",title:"Hepatitis B",sub:"The Silent Liver War",status:"soon",icon:"\uD83E\uDEC0",dur:"10h",modules:4},
      {id:"hepc",title:"Hepatitis C",sub:"The Quiet Epidemic",status:"soon",icon:"\uD83E\uDEC0",dur:"8h",modules:4},
      {id:"seps",title:"Sepsis (Adult)",sub:"The Immune Storm",status:"soon",icon:"\u26A1",dur:"10h",modules:4},
      {id:"cov",title:"COVID-19 & Post-COVID",sub:"Lessons from the Pandemic",status:"soon",icon:"\uD83E\uDDA0",dur:"10h",modules:4},
      {id:"mpox",title:"Mpox",sub:"The Emerging Threat",status:"soon",icon:"\u26A0\uFE0F",dur:"6h",modules:3},
      {id:"lass",title:"Lassa Fever",sub:"West Africa's Haemorrhagic Fever",status:"soon",icon:"\uD83D\uDD34",dur:"6h",modules:3},
      {id:"ebola",title:"Ebola & Viral Haemorrhagic Fevers",sub:"Maximum Containment",status:"soon",icon:"\u26A0\uFE0F",dur:"8h",modules:4},
      {id:"rab",title:"Rabies",sub:"Prevention or Death",status:"soon",icon:"\uD83D\uDC15",dur:"5h",modules:3},
      {id:"sch",title:"Schistosomiasis",sub:"The Worm in the Water",status:"soon",icon:"\uD83E\uDEB1",dur:"6h",modules:3},
      {id:"oncho",title:"Onchocerciasis",sub:"River Blindness",status:"soon",icon:"\uD83D\uDC41\uFE0F",dur:"5h",modules:3},
    ]},
    {name:"Non-Communicable Diseases",icon:"\u2764\uFE0F",courses:[
      {id:"htn",title:"Hypertension",sub:"The Silent Killer",status:"soon",icon:"\uD83D\uDC93",dur:"10h",modules:4},
      {id:"dm",title:"Diabetes Mellitus",sub:"Type 1 & 2 Complete",status:"soon",icon:"\uD83C\uDF6C",dur:"14h",modules:6},
      {id:"scd",title:"Sickle Cell Disease",sub:"A Warrior's Journey",status:"soon",icon:"\uD83E\uDE78",dur:"12h",modules:5},
      {id:"str",title:"Stroke",sub:"Brain Under Attack",status:"soon",icon:"\uD83E\uDDE0",dur:"12h",modules:5},
      {id:"hf",title:"Heart Failure",sub:"When the Pump Fails",status:"soon",icon:"\uD83D\uDC94",dur:"12h",modules:5},
      {id:"acs",title:"Acute Coronary Syndrome",sub:"The Heart Attack Spectrum",status:"soon",icon:"\u2764\uFE0F",dur:"10h",modules:4},
      {id:"ckd",title:"Chronic Kidney Disease",sub:"Protecting What Remains",status:"soon",icon:"\uD83E\uDEB8",dur:"10h",modules:4},
      {id:"asth",title:"Asthma",sub:"Breathing Through the Storm",status:"soon",icon:"\uD83E\uDEB1",dur:"8h",modules:4},
      {id:"copd",title:"COPD",sub:"Lungs Under Pressure",status:"soon",icon:"\uD83E\uDEB1",dur:"8h",modules:4},
      {id:"epi",title:"Epilepsy",sub:"Mastering the Seizure",status:"soon",icon:"\u26A1",dur:"8h",modules:4},
      {id:"an",title:"Anaemia",sub:"All Types Covered",status:"soon",icon:"\uD83E\uDE78",dur:"8h",modules:4},
      {id:"thy",title:"Thyroid Disorders",sub:"The Butterfly Gland",status:"soon",icon:"\uD83E\uDD8B",dur:"8h",modules:4},
      {id:"lc",title:"Liver Cirrhosis",sub:"End-Stage Liver Disease",status:"soon",icon:"\uD83E\uDEC0",dur:"10h",modules:4},
      {id:"pud",title:"Peptic Ulcer Disease",sub:"Fire in the Gut",status:"soon",icon:"\uD83D\uDD25",dur:"6h",modules:3},
      {id:"ra",title:"Rheumatoid Arthritis",sub:"The Autoimmune Attack",status:"soon",icon:"\uD83E\uDDB4",dur:"8h",modules:4},
      {id:"sle",title:"Systemic Lupus Erythematosus",sub:"The Great Imitator",status:"soon",icon:"\uD83E\uDD8B",dur:"10h",modules:4},
    ]},
    {name:"Oncology",icon:"\uD83C\uDF97\uFE0F",courses:[
      {id:"cc",title:"Cervical Cancer",sub:"Prevention to Treatment",status:"soon",icon:"\uD83C\uDF97\uFE0F",dur:"10h",modules:4},
      {id:"bc",title:"Breast Cancer",sub:"Early Detection Saves Lives",status:"soon",icon:"\uD83C\uDF80",dur:"10h",modules:4},
      {id:"prc",title:"Prostate Cancer",sub:"The Silent Progression",status:"soon",icon:"\uD83C\uDF97\uFE0F",dur:"8h",modules:4},
      {id:"crc",title:"Colorectal Cancer",sub:"The Preventable Cancer",status:"soon",icon:"\uD83D\uDD34",dur:"8h",modules:4},
      {id:"lymp",title:"Lymphoma",sub:"Hodgkin & Non-Hodgkin",status:"soon",icon:"\uD83D\uDD35",dur:"10h",modules:4},
    ]},
    {name:"Mental Health",icon:"\uD83E\uDDE0",courses:[
      {id:"dep",title:"Depression",sub:"Beyond Sadness",status:"soon",icon:"\uD83E\uDDE0",dur:"8h",modules:4},
      {id:"schz",title:"Schizophrenia",sub:"Rebuilding Reality",status:"soon",icon:"\uD83D\uDD2E",dur:"8h",modules:4},
      {id:"bpd",title:"Bipolar Disorder",sub:"The Mood Spectrum",status:"soon",icon:"\uD83C\uDF0A",dur:"8h",modules:4},
      {id:"sud",title:"Substance Use Disorders",sub:"The Brain Hijacked",status:"soon",icon:"\u26A0\uFE0F",dur:"8h",modules:4},
      {id:"ptsd",title:"PTSD",sub:"Healing After Trauma",status:"soon",icon:"\uD83D\uDC99",dur:"8h",modules:4},
    ]},
    {name:"Emergency Medicine",icon:"\uD83D\uDEA8",courses:[
      {id:"ana",title:"Anaphylaxis",sub:"Seconds Count",status:"soon",icon:"\u26A1",dur:"5h",modules:3},
      {id:"pois",title:"Poisoning & Toxicology",sub:"The Antidote Guide",status:"soon",icon:"\u2620\uFE0F",dur:"8h",modules:4},
      {id:"tra",title:"Trauma & Polytrauma",sub:"The Golden Hour",status:"soon",icon:"\uD83D\uDE91",dur:"10h",modules:4},
      {id:"burn",title:"Burns Management",sub:"From First Aid to ICU",status:"soon",icon:"\uD83D\uDD25",dur:"8h",modules:4},
      {id:"drown",title:"Drowning & Asphyxia",sub:"Airway Is Everything",status:"soon",icon:"\uD83D\uDCA7",dur:"5h",modules:3},
    ]},
   ]},
  {id:"phi",num:"02",icon:"\uD83D\uDC8A",name:"Pharmacology Institute",tagline:"From molecule to medicine. The complete pharmacology school.",color:"#6E2C00",type:"education",
   desc:"A dedicated pharmacology school offering everything from foundational science to advanced clinical pharmacology, drug discovery and precision medicine.",
   categories:[
    {name:"Core Pharmacology",icon:"\uD83E\uDDEA",courses:[
      {id:"gp",title:"General Pharmacology",sub:"The Foundation",status:"soon",icon:"\uD83D\uDC8A",dur:"14h",modules:6},
      {id:"np",title:"Neuropharmacology",sub:"Drugs & the Brain",status:"soon",icon:"\uD83E\uDDE0",dur:"12h",modules:5},
      {id:"cvp",title:"Cardiovascular Pharmacology",sub:"Drugs for the Heart",status:"soon",icon:"\u2764\uFE0F",dur:"12h",modules:5},
      {id:"amp",title:"Antimicrobial Pharmacology",sub:"Fighting Infection",status:"soon",icon:"\uD83E\uDDA0",dur:"12h",modules:5},
      {id:"cpk",title:"Clinical Pharmacokinetics",sub:"How Drugs Move",status:"soon",icon:"\uD83D\uDCC8",dur:"10h",modules:4},
      {id:"tox",title:"Toxicology",sub:"When Drugs Harm",status:"soon",icon:"\u2620\uFE0F",dur:"10h",modules:4},
    ]},
    {name:"Advanced Pharmacology",icon:"\uD83D\uDD2C",courses:[
      {id:"dd",title:"Drug Discovery",sub:"From Lab to Lead",status:"soon",icon:"\uD83D\uDD2D",dur:"12h",modules:5},
      {id:"ddv",title:"Drug Development",sub:"Clinical Trials to Approval",status:"soon",icon:"\uD83D\uDCCB",dur:"12h",modules:5},
      {id:"pgx",title:"Pharmacogenomics",sub:"Your Genes, Your Drugs",status:"soon",icon:"\uD83E\uDDEC",dur:"10h",modules:4},
      {id:"prm",title:"Precision Medicine",sub:"Right Drug, Right Patient",status:"soon",icon:"\uD83C\uDFAF",dur:"10h",modules:4},
      {id:"aip",title:"AI in Pharmacology",sub:"The Future of Drug Science",status:"soon",icon:"\uD83E\uDD16",dur:"8h",modules:4},
    ]},
    {name:"Flagship Programmes",icon:"\uD83C\uDFC6",courses:[
      {id:"mp",title:"Mastering Pharmacology",sub:"Complete Fellowship Programme",status:"soon",icon:"\uD83C\uDFC6",dur:"60h",modules:20,featured:true},
      {id:"cpf",title:"Clinical Pharmacology Fellowship",sub:"Advanced Practice",status:"soon",icon:"\uD83C\uDF93",dur:"40h",modules:15,featured:true},
      {id:"dda",title:"Drug Discovery Accelerator",sub:"Innovate & Create",status:"soon",icon:"\uD83D\uDE80",dur:"30h",modules:12,featured:true},
      {id:"tpp",title:"Translational Pharmacology",sub:"Bench to Bedside",status:"soon",icon:"\uD83D\uDD2C",dur:"30h",modules:10,featured:true},
    ]},
   ]},
  {id:"med",num:"03",icon:"\uD83C\uDF93",name:"Medical School",tagline:"Preclinical to clinical — the complete medical curriculum.",color:"#003087",type:"education",
   desc:"Comprehensive medical education covering all preclinical sciences and clinical disciplines.",
   categories:[
    {name:"Preclinical Sciences",icon:"\uD83D\uDD2C",courses:[
      {id:"anat",title:"Anatomy",sub:"The Architecture of Life",status:"soon",icon:"\uD83E\uDDB4",dur:"20h",modules:8},
      {id:"phys",title:"Physiology",sub:"The Body in Action",status:"soon",icon:"\u26A1",dur:"20h",modules:8},
      {id:"bioc",title:"Biochemistry",sub:"Chemistry of Life",status:"soon",icon:"\uD83E\uDDEA",dur:"18h",modules:7},
      {id:"path",title:"Pathology",sub:"Disease Under the Microscope",status:"soon",icon:"\uD83D\uDD2C",dur:"18h",modules:7},
      {id:"pharm2",title:"Pharmacology",sub:"Drugs & Disease",status:"soon",icon:"\uD83D\uDC8A",dur:"16h",modules:6},
      {id:"micro2",title:"Microbiology",sub:"The Invisible World",status:"soon",icon:"\uD83E\uDDA0",dur:"16h",modules:6},
    ]},
    {name:"Clinical Medicine",icon:"\uD83E\uDE7A",courses:[
      {id:"im",title:"Internal Medicine",sub:"The Complete Physician",status:"soon",icon:"\uD83E\uDE7A",dur:"30h",modules:12},
      {id:"surg",title:"Surgery",sub:"The Art of Cutting",status:"soon",icon:"\uD83D\uDD2A",dur:"25h",modules:10},
      {id:"paed",title:"Paediatrics",sub:"Medicine for Children",status:"soon",icon:"\uD83D\uDC76",dur:"20h",modules:8},
      {id:"og",title:"Obstetrics & Gynaecology",sub:"Women's Health",status:"soon",icon:"\uD83E\uDD30",dur:"20h",modules:8},
      {id:"psy",title:"Psychiatry",sub:"The Medicine of the Mind",status:"soon",icon:"\uD83E\uDDE0",dur:"16h",modules:6},
      {id:"emed",title:"Emergency Medicine",sub:"Critical Decisions",status:"soon",icon:"\uD83D\uDEA8",dur:"16h",modules:6},
    ]},
   ]},
  {id:"sim",num:"04",icon:"\uD83E\uDD16",name:"Clinical Simulator",tagline:"Practice on virtual patients. Make mistakes safely.",color:"#0d5e6e",type:"tool",
   desc:"An AI-powered virtual patient platform where you practice clinical reasoning, history taking, examination, investigations, diagnosis and treatment planning — without risk to real patients.",
   toolFeatures:[
    {icon:"\uD83D\uDC64",name:"AI Patients",desc:"Realistic virtual patients with full histories, symptoms, and adaptive responses"},
    {icon:"\uD83D\uDDE3\uFE0F",name:"History Taking",desc:"Guided clinical interviews that respond naturally to your questions"},
    {icon:"\uD83D\uDD2C",name:"Investigation Ordering",desc:"Order labs, imaging, and procedures — receive real results"},
    {icon:"\uD83C\uDFAF",name:"Clinical Reasoning",desc:"Step-by-step diagnostic frameworks with instant expert feedback"},
    {icon:"\uD83D\uDC8A",name:"Treatment Planning",desc:"Prescribe, monitor, and manage complications in a safe environment"},
    {icon:"\uD83D\uDCCA",name:"Performance Analytics",desc:"Detailed feedback on every clinical decision you make"},
   ],
   categories:[{name:"Simulation Cases",icon:"\uD83E\uDE7A",courses:[
    {id:"sim_obs",title:"Obstetric Emergencies",sub:"12 Critical Cases",status:"soon",icon:"\uD83E\uDD30",dur:"6h",modules:12},
    {id:"sim_em",title:"Emergency Medicine Cases",sub:"20 High-Stakes Scenarios",status:"soon",icon:"\uD83D\uDEA8",dur:"8h",modules:20},
    {id:"sim_med",title:"General Medicine Cases",sub:"30 Diagnostic Puzzles",status:"soon",icon:"\uD83E\uDE7A",dur:"10h",modules:30},
    {id:"sim_surg",title:"Surgical Cases",sub:"15 Operative Decisions",status:"soon",icon:"\uD83D\uDD2A",dur:"6h",modules:15},
    {id:"sim_paed",title:"Paediatric Cases",sub:"20 Child Health Scenarios",status:"soon",icon:"\uD83D\uDC76",dur:"8h",modules:20},
    {id:"sim_pharm",title:"Pharmacotherapy Cases",sub:"Drug Management Scenarios",status:"soon",icon:"\uD83D\uDC8A",dur:"6h",modules:15},
   ]}]},
  {id:"skills",num:"05",icon:"\uD83D\uDEE0\uFE0F",name:"Skills Lab",tagline:"See it. Practice it. Master it.",color:"#1a5276",type:"tool",
   desc:"Interactive practical training for clinical skills, OSCE preparation, procedure simulations and case walkthroughs.",
   toolFeatures:[
    {icon:"\uD83D\uDCCB",name:"OSCE Preparation",desc:"Structured stations with mark schemes and video demonstrations"},
    {icon:"\uD83E\uDE7A",name:"Clinical Skills",desc:"Examination techniques for every system with step-by-step guidance"},
    {icon:"\uD83D\uDD27",name:"Procedure Simulations",desc:"IV access, catheterisation, lumbar puncture, intubation and more"},
    {icon:"\uD83D\uDCD6",name:"Case Walkthroughs",desc:"Complete clinical cases with reasoning frameworks"},
    {icon:"\uD83C\uDF9E\uFE0F",name:"Video Library",desc:"Expert demonstrations of every procedure and examination"},
    {icon:"\u2705",name:"Competency Checklists",desc:"Track your practical skill attainment with digital sign-off"},
   ],
   categories:[{name:"Skills Modules",icon:"\uD83D\uDEE0\uFE0F",courses:[
    {id:"sk_exam",title:"Clinical Examination Masterclass",sub:"All Systems",status:"soon",icon:"\uD83E\uDE7A",dur:"10h",modules:6},
    {id:"sk_osce",title:"OSCE Station Bank",sub:"200+ Practice Stations",status:"soon",icon:"\uD83D\uDCCB",dur:"20h",modules:12},
    {id:"sk_proc",title:"Clinical Procedures",sub:"Step-by-Step",status:"soon",icon:"\uD83D\uDD27",dur:"8h",modules:8},
    {id:"sk_comm",title:"Communication Skills",sub:"Breaking Bad News & More",status:"soon",icon:"\uD83D\uDDE3\uFE0F",dur:"6h",modules:5},
    {id:"sk_ecg",title:"ECG Interpretation",sub:"100 Tracings",status:"soon",icon:"\u2764\uFE0F",dur:"6h",modules:4},
    {id:"sk_xray",title:"Radiology for Clinicians",sub:"X-ray, CT, MRI Basics",status:"soon",icon:"\uD83E\uDDB4",dur:"8h",modules:5},
   ]}]},
  {id:"ai",num:"06",icon:"\uD83E\uDDE0",name:"AI Tutor",tagline:"Your personal learning companion. Available 24/7.",color:"#5b2d8e",type:"tool",
   desc:"A personalised AI learning companion that explains concepts, generates quizzes, creates study plans, monitors progress and adapts to your learning style.",
   toolFeatures:[
    {icon:"\uD83D\uDCAC",name:"Concept Explainer",desc:"Ask anything about any medical topic — get clear, evidence-based answers"},
    {icon:"\uD83D\uDCDD",name:"Quiz Generator",desc:"Auto-generate MCQs, SAQs and clinical scenarios from any topic"},
    {icon:"\uD83D\uDCC5",name:"Study Planner",desc:"Personalised exam prep plans based on your timeline and goals"},
    {icon:"\uD83D\uDCCA",name:"Progress Monitor",desc:"Track what you know, what you're improving, and what needs work"},
    {icon:"\uD83C\uDFAF",name:"Weak Area Identifier",desc:"Pinpoint exactly where your knowledge gaps are"},
    {icon:"\uD83D\uDD04",name:"Adaptive Learning",desc:"Content adjusts in real-time to your performance and pace"},
   ],
   categories:[{name:"AI-Powered Learning Tools",icon:"\uD83E\uDD16",courses:[
    {id:"ai_quiz",title:"Smart Quiz Engine",sub:"Unlimited MCQ Practice",status:"soon",icon:"\uD83D\uDCDD",dur:"self-paced",modules:0},
    {id:"ai_flash",title:"Intelligent Flashcards",sub:"Spaced Repetition System",status:"soon",icon:"\uD83C\uDCCF",dur:"self-paced",modules:0},
    {id:"ai_chat",title:"Ask the Consultant",sub:"24/7 Medical Q&A",status:"soon",icon:"\uD83D\uDCAC",dur:"self-paced",modules:0},
    {id:"ai_plan",title:"Exam Prep Planner",sub:"Customised Study Schedules",status:"soon",icon:"\uD83D\uDCC5",dur:"self-paced",modules:0},
    {id:"ai_case",title:"Case-Based Reasoning",sub:"AI-Generated Clinical Cases",status:"soon",icon:"\uD83C\uDFAF",dur:"self-paced",modules:0},
   ]}]},
  {id:"pass",num:"07",icon:"\uD83C\uDFC5",name:"Competency Passport",tagline:"Your verified professional portfolio. Carry it everywhere.",color:"#a8892e",type:"tool",
   desc:"A digital professional portfolio storing your verified skills, certificates, competencies, clinical experiences and research activities.",
   toolFeatures:[
    {icon:"\uD83C\uDF93",name:"Certificate Vault",desc:"All your LegonMed certificates in one verified, shareable location"},
    {icon:"\u2705",name:"Competency Records",desc:"Documented and verified clinical competencies"},
    {icon:"\uD83C\uDFE5",name:"Clinical Experience Log",desc:"Track placements, rotations and clinical hours"},
    {icon:"\uD83D\uDD2C",name:"Research Portfolio",desc:"Publications, abstracts, posters and presentations"},
    {icon:"\uD83D\uDCE4",name:"Share & Export",desc:"Share with employers, regulators and institutions"},
    {icon:"\uD83D\uDD12",name:"Verified & Secure",desc:"Blockchain-ready credential verification"},
   ],
   categories:[{name:"Passport Features",icon:"\uD83C\uDFC5",courses:[
    {id:"p_cert",title:"Certificate Management",sub:"Store & Share Credentials",status:"soon",icon:"\uD83C\uDF93",dur:"tool",modules:0},
    {id:"p_comp",title:"Competency Tracker",sub:"Clinical Skills Log",status:"soon",icon:"\u2705",dur:"tool",modules:0},
    {id:"p_cpd",title:"CPD Record",sub:"Continuing Education Log",status:"soon",icon:"\uD83D\uDCCA",dur:"tool",modules:0},
    {id:"p_res",title:"Research Portfolio",sub:"Publications & Presentations",status:"soon",icon:"\uD83D\uDD2C",dur:"tool",modules:0},
   ]}]},
  {id:"res",num:"08",icon:"\uD83D\uDCDA",name:"Research Hub",tagline:"Think like a scientist. Write like a scholar.",color:"#2c6e49",type:"tool",
   desc:"A complete research training ecosystem covering methods, statistics, scientific writing, grant writing, publication mentorship and collaborations.",
   toolFeatures:[
    {icon:"\uD83D\uDCCA",name:"Research Methods",desc:"Quantitative, qualitative and mixed methods training"},
    {icon:"\uD83D\uDCD0",name:"Biostatistics",desc:"From descriptive stats to advanced regression — practical and applied"},
    {icon:"\u270D\uFE0F",name:"Scientific Writing",desc:"IMRaD structure, journal targeting and writing for publication"},
    {icon:"\uD83D\uDCB0",name:"Grant Writing",desc:"Craft winning proposals for NIH, Wellcome, GCRF and more"},
    {icon:"\uD83E\uDD1D",name:"Research Collaborations",desc:"Connect with researchers across Africa and globally"},
    {icon:"\uD83D\uDCD6",name:"Publication Mentorship",desc:"Guided support from submission to acceptance"},
   ],
   categories:[{name:"Research Training Courses",icon:"\uD83D\uDCDA",courses:[
    {id:"r_meth",title:"Research Methods Fundamentals",sub:"Design Your Study",status:"soon",icon:"\uD83D\uDCCA",dur:"12h",modules:5},
    {id:"r_stat",title:"Biostatistics for Health Research",sub:"Numbers Tell Stories",status:"soon",icon:"\uD83D\uDCD0",dur:"12h",modules:5},
    {id:"r_write",title:"Scientific Writing Masterclass",sub:"Write to Publish",status:"soon",icon:"\u270D\uFE0F",dur:"10h",modules:4},
    {id:"r_grant",title:"Grant Writing Workshop",sub:"Fund Your Research",status:"soon",icon:"\uD83D\uDCB0",dur:"8h",modules:4},
    {id:"r_sys",title:"Systematic Reviews & Meta-Analysis",sub:"Evidence Synthesis",status:"soon",icon:"\uD83D\uDD0D",dur:"10h",modules:4},
    {id:"r_epi",title:"Epidemiology Essentials",sub:"Population Health Science",status:"soon",icon:"\uD83C\uDF0D",dur:"10h",modules:4},
   ]}]},
  {id:"cpd",num:"09",icon:"\uD83D\uDCDC",name:"Continuing Professional Development",tagline:"Stay current. Stay licensed. Stay excellent.",color:"#1a237e",type:"tool",
   desc:"Accredited CPD courses, professional certifications, CPD tracking and license renewal support for licensed healthcare professionals.",
   toolFeatures:[
    {icon:"\uD83D\uDCCA",name:"CPD Tracker",desc:"Automatic CPD point accumulation with accredited courses"},
    {icon:"\uD83C\uDFE5",name:"Accredited Courses",desc:"GMC, MCGH, PCG and internationally recognised CPD"},
    {icon:"\uD83C\uDF93",name:"Professional Certifications",desc:"Specialty-specific advanced certifications"},
    {icon:"\uD83D\uDD04",name:"License Renewal",desc:"Track requirements and deadlines for your professional body"},
    {icon:"\uD83D\uDCDC",name:"CPD Certificates",desc:"Instant digital certificates for every completed module"},
    {icon:"\uD83C\uDF0D",name:"Global Recognition",desc:"CPD recognised by African and international medical councils"},
   ],
   categories:[{name:"CPD Programmes",icon:"\uD83D\uDCDC",courses:[
    {id:"cpd_em",title:"Emergency Medicine CPD",sub:"Annual Recertification",status:"soon",icon:"\uD83D\uDEA8",dur:"6h",modules:3},
    {id:"cpd_ob",title:"Obstetric Emergencies CPD",sub:"Safe Motherhood",status:"soon",icon:"\uD83E\uDD30",dur:"6h",modules:3},
    {id:"cpd_pharm",title:"Clinical Pharmacology Update",sub:"New Drugs & Evidence",status:"soon",icon:"\uD83D\uDC8A",dur:"4h",modules:2},
    {id:"cpd_inf",title:"Infection Control CPD",sub:"AMR & Prevention",status:"soon",icon:"\uD83E\uDDA0",dur:"4h",modules:2},
    {id:"cpd_eth",title:"Medical Ethics & Law",sub:"Professional Obligations",status:"soon",icon:"\u2696\uFE0F",dur:"4h",modules:2},
    {id:"cpd_lead",title:"Clinical Leadership",sub:"Lead Your Team",status:"soon",icon:"\uD83D\uDC51",dur:"6h",modules:3},
    {id:"cpd_dig",title:"Digital Health & AI in Practice",sub:"The Future of Medicine",status:"soon",icon:"\uD83E\uDD16",dur:"4h",modules:2},
   ]}]},
];

